const CertifiedMembersData =[
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Anisha",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Mrs Anna Chandy",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Annie Cariapa",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Aruna Gopakumar",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Chitra Ravi",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Mr Deepak Dhananjaya",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Gunjan Zutshi",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Haseena Abdulla",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Mr I A Mohanraj",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Jalaja Pillai",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Mr Joy Roshan",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Dr Marina Rajan Joseph",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Prathitha Gangadharan",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Priya Veeraraghavan",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Ragini Rao",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Mr Raguraman k",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Reshma Prakash",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Sailaja Manacha",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Sarmishta Mani",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Seema Pradhan",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Mrs Sudha Thimmaiah",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Mr. Suriyaprakash C",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Susan George",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
    {
        image:"images/certified-members-image1.jpg",
        title:"Ms Sushma M.R",
        Qualification1:"Qualification",
        Qualificationdes1:"Certified Transactional Analyst (CTA)",
        Qualification2:"Field of Training:",
        Qualificationdes2:"Psychotherapy",
        Qualification3:"Institute Name:",
        Qualificationdes3:"Bliss",
        Qualification4:"Contact Number:",
        Qualificationdes4:"+91 9820305886",
        Qualification5:"Email:",
        Qualificationdes5:"anisha.pandya@gmail.com",
        Qualification6:"Website:",
        Qualificationdes6:"www.anishapandya.com"
    },
]

export default CertifiedMembersData;